"""
Pydantic models for structured AI responses and API validation.
"""
from pydantic import BaseModel, Field
from typing import List, Optional


class JobAnalysisRequest(BaseModel):
    """Request model for job description analysis."""
    job_description: str = Field(..., min_length=50, description="Job description text")


class Skill(BaseModel):
    """Individual skill extracted from job description."""
    name: str = Field(..., description="Skill name")
    importance: str = Field(..., description="Priority level: Critical, Important, or Nice-to-have")
    category: str = Field(..., description="Category: Technical, Soft Skill, or Domain Knowledge")


class JobAnalysis(BaseModel):
    """Structured job analysis output from AI agent."""
    role_title: str = Field(..., description="Job role title")
    company_type: str = Field(..., description="Type of company (e.g., Startup, Enterprise, etc.)")
    experience_level: str = Field(..., description="Required experience level")
    key_skills: List[Skill] = Field(..., description="List of key skills required")
    difficulty_level: str = Field(..., description="Overall difficulty: Entry, Intermediate, or Advanced")
    summary: str = Field(..., description="Brief summary of the role")


class StudyTopic(BaseModel):
    """Individual study topic in the plan."""
    topic: str = Field(..., description="Topic name")
    description: str = Field(..., description="What to study")
    estimated_hours: int = Field(..., ge=1, le=100, description="Estimated study time in hours")
    resources: List[str] = Field(..., description="Recommended learning resources")
    priority: int = Field(..., ge=1, le=5, description="Priority level (1=highest, 5=lowest)")


class StudyPlan(BaseModel):
    """Personalized study plan generated by AI agent."""
    total_duration_hours: int = Field(..., description="Total estimated study time")
    topics: List[StudyTopic] = Field(..., description="Ordered list of topics to study")
    preparation_strategy: str = Field(..., description="Overall strategy for preparation")
    timeline_suggestion: str = Field(..., description="Suggested timeline (e.g., '2 weeks', '1 month')")


class StudyPlanRequest(BaseModel):
    """Request model for study plan generation."""
    job_analysis: JobAnalysis = Field(..., description="Previously analyzed job data")
    available_time_hours: Optional[int] = Field(40, description="Hours available per week")


class PracticeQuestion(BaseModel):
    """Individual practice question."""
    question: str = Field(..., description="The practice question")
    type: str = Field(..., description="Question type: Technical, Behavioral, or Situational")
    difficulty: str = Field(..., description="Difficulty: Easy, Medium, or Hard")
    hints: List[str] = Field(..., description="Hints to help answer the question")
    key_points: List[str] = Field(..., description="Key points to cover in the answer")


class QuestionSet(BaseModel):
    """Set of practice questions generated by AI agent."""
    questions: List[PracticeQuestion] = Field(..., description="List of practice questions")
    focus_area: str = Field(..., description="Main focus area of these questions")


class QuestionRequest(BaseModel):
    """Request model for practice question generation."""
    job_analysis: JobAnalysis = Field(..., description="Job analysis data")
    topic: str = Field(..., description="Specific topic to focus on")
    count: int = Field(5, ge=1, le=10, description="Number of questions to generate")


class AnswerEvaluation(BaseModel):
    """AI evaluation of a practice answer."""
    score: int = Field(..., ge=0, le=100, description="Score out of 100")
    strengths: List[str] = Field(..., description="Strong points in the answer")
    improvements: List[str] = Field(..., description="Areas for improvement")
    suggested_answer: str = Field(..., description="Example of a strong answer")
    overall_feedback: str = Field(..., description="Overall feedback summary")


class EvaluationRequest(BaseModel):
    """Request model for answer evaluation."""
    question: str = Field(..., description="The practice question")
    user_answer: str = Field(..., min_length=10, description="User's answer to evaluate")
    expected_key_points: List[str] = Field(..., description="Key points that should be covered")


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = "healthy"
    service: str = "Interview Prep AI Agent"
